#!/usr/bin/env bash


set -e

if [[ -z "$NIXOS_CONFIG_DIR" ]]; then
    echo "\$NIXOS_CONFIG_DIR is not set. Please set it to the directory containing your configuration.nix file"
    exit 1
fi

# cd to your config dir
pushd "$NIXOS_CONFIG_DIR"

# Edit your config
kate -b "admin:$(pwd)/configuration.nix" >/dev/null

# Autoformat your nix files
alejandra . >/dev/null

# Shows your changes
git diff -U0 *.nix

echo "NixOS Rebuilding..."

# Rebuild, output simplified errors, log trackebacks
sudo nixos-rebuild switch -I nixos-config="$(pwd)/configuration.nix" &>nixos-switch.log || (cat nixos-switch.log | grep --color error && false)

# Get current generation metadata
current=$(nixos-rebuild list-generations | grep current)

# Commit all changes witih the generation metadata
git commit -am "$current"

# Back to where you were
popd

# Notify all OK!
notify-send -e "NixOS Rebuilt OK!" --icon=software-update-available
